#include	<stdio.h>
#include	<string.h>
#include	"ab2c_run.h"
#include	"ab2c_var.h"
int a=1;
int b=2;
char ch;
int fp=3;
int na[21];
char	s[32];

void _sxb_start(void) {
	printf("%d\n", asc("a"));
	printf("%f\n", atof("3.14"));
	printf("%d\n", atoi("3.14"));
	printf("%f\n", abs(3.140000));
	printf("%f\n", atan(0.500000));
	printf("%s\n", _sxb_bin(123));
	printf("%s\n", _sxb_chrS(12));
	printf("%f\n", cos(3.141926 / 2));
	printf("%d\n", dskf(67));
	printf("%s\n", dataS());
	printf("%s\n", dayS());
	printf("%f\n", exp(1.234000));
	printf("%d\n", a);
	printf("%d\n", b);
	printf("%s\n", ecvt(1.234000, 1, &a, &b));
	printf("%d\n", fclose(fp));
	printf("%d\n", flocseall());
	printf("%s\n", fcvt(123.456000, 2, &a, &b));
	printf("%d\n", TSDeleteP("delete.txt"));
	printf("%d\n", feof(fp));
	printf("%d\n", _sxb_fgetc(fp));
	printf("%f\n", fix(123.456000));
	printf("%d\n", _sxb_fopen("test.txt","r"));
	printf("%d\n", _sxb_fputc(ch,fp));
	printf("%d\n", _sxb_fread(na, sizeof(na), 2,fp));
	printf("%d\n", _sxb_freads(s, sizeof(s) ,fp));
	printf("%d\n", _sxb_frename("oldname.txt","newname.txt"));
	printf("%d\n", _sxb_fseek(fp,1,2));
	printf("%d\n", _sxb_fwrite(na, sizeof(na), 12,fp));
	printf("%d\n", _sxb_fwrites(s,fp));
	printf("%s\n", gcvt(123.400000,2));
	printf("%s\n", _sxb_hex(123));
	printf("%d\n", int(123.400000));
	printf("%s\n", itoa(123));
	printf("%d\n", instr(2,"hello","world"));
	printf("%d\n", isalnum(97));
	printf("%d\n", isalpha(97));
	printf("%d\n", isascii(97));
	printf("%d\n", iscntrl(97));
	printf("%d\n", isdigit(97));
	printf("%d\n", isgraph(97));
	printf("%d\n", islower(97));
	printf("%d\n", isprint(97));
	printf("%d\n", ispunct(97));
	printf("%d\n", isspace(97));
	printf("%d\n", isupper(97));
	printf("%d\n", isxdigit(97));
	printf("%d\n", len("hello"));
	printf("%f\n", log(1.234500));
	printf("%s\n", left$("hello",2));
	printf("%s\n", _sxb_mid("hello world",1,2));
	printf("%s\n", _sxb_mirror("hello world"));
	printf("%c\n", mouse(2));
	printf("%s\n", _sxb_oct(123));
	printf("%f\n", pi(1));
	printf("%f\n", pi(2));
	printf("%f\n", pow(1.200000,3.400000));
	printf("%d\n", rand());
	printf("%f\n", rnd());
	printf("%s\n", _sxb_rightS("hello",2));
	printf("%s\n", _sxb_str(123.450000));
	printf("%f\n", sgn(12.345000));
	printf("%f\n", sin(3.141500));
	printf("%f\n", sqr(1.234000));
	printf("%s\n", _sxb_spaceS(10));
	printf("%d\n", strchr("hello",104));
	printf("%d\n", strcspn("hello world","hello"));
	printf("%s\n", _sxb_stringS(10,"hello"));
	printf("%d\n", strlen("hello"));
	printf("%d\n", strrchr("hello",3));
	printf("%d\n", strspn("hello","hello"));
	printf("%s\n", strtok("hello","hello"));
	printf("%s\n", strlwr(s, sizeof(s)));
	printf("%s\n", strnset(s, sizeof(s) ,1 ,2));
	printf("%s\n", strrev(s, sizeof(s)));
	printf("%s\n", strset(s, sizeof(s) ,2));
	printf("%s\n", strupr(s, sizeof(s)));
	printf("%d\n", toascii(97));
	printf("%d\n", tolower(65));
	printf("%d\n", toupper(97));
	printf("%f\n", tan(1.234000));
	printf("%s\n", timeS());
	printf("%f\n", val("&habcd"));
};